name    'alkivi-mcollective'
version '0.0.1'
source 'https://github.com/alkivi-sas/puppet-mcollective'
author 'alkivi'
license 'LGPLv3'
summary 'Controls mcollective deploiement on puppet node'
description 'Setup mcollective deploiement on puppet note'
project_page 'https://github.com/alkivi-sas/puppet-mcollective'
#dependency 'puppetlabs/stdlib', '>3.x'
#dependency 'puppetlabs/concat', '1.0.0'
#dependency 'puppetlabs/apache', '>0.x'
#dependency 'alkivi/alkivi_base', '>0.x'
